# Generated by Django 4.2.2 on 2023-08-26 02:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "publication_year",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(2023)]
                    ),
                ),
                ("author", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=500)),
                ("image", models.ImageField(upload_to="images/books/")),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Active"), ("2", "Inactive")],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=500)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("image", models.ImageField(upload_to="images/category/")),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("fullname", models.CharField(max_length=500)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ReaderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Wait"), ("2", "Accept"), ("3", "Decline")],
                        default="1",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=500)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("identity", models.CharField(max_length=9)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "date_of_birth",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("1", "MALE"), ("2", "FEMALE")],
                        max_length=2,
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        default="images/avatars/default.jpg",
                        upload_to="images/avatars/",
                    ),
                ),
                ("first_time", models.BooleanField(default=True)),
                (
                    "bio",
                    models.CharField(
                        default="Edit profile for more.", max_length=255, null=True
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("READER", "Reader"),
                            ("LIBRARIAN", "Librarian"),
                        ],
                        default="READER",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField(max_length=500)),
                ("main_content", models.TextField(max_length=5000)),
                ("image_blog", models.ImageField(upload_to="images/post/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "writer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ad.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("publication_year", models.IntegerField()),
                ("author", models.CharField(max_length=500)),
                ("description", models.TextField(max_length=500)),
                ("image", models.ImageField(upload_to="images/books_request/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Wait"), ("2", "Accept"), ("3", "Decline")],
                        default="1",
                        max_length=2,
                    ),
                ),
                ("category", models.ManyToManyField(to="ad.category")),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ad.language",
                    ),
                ),
                (
                    "sourcetype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ad.sourcetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(to="ad.category"),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ad.language",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="sourcetype",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ad.sourcetype",
            ),
        ),
        migrations.CreateModel(
            name="LoanTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_loan", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "date_expired",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 9, 2, 2, 6, 16, 186672, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "overdue",
                    models.CharField(
                        choices=[("0", "No"), ("1", "Yes")], default="0", max_length=2
                    ),
                ),
                (
                    "returned",
                    models.CharField(
                        choices=[("0", "No"), ("1", "Yes")], default="0", max_length=2
                    ),
                ),
                ("renew_limit", models.IntegerField(default=1)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ad.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book", "date_loan")},
            },
        ),
    ]
