# Generated by Django 4.2.2 on 2023-08-06 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 13, 9, 59, 16, 303625, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
