# Generated by Django 4.2.2 on 2023-06-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_created',
        ),
    ]
