# Generated by Django 4.2.2 on 2023-06-28 04:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0002_librarian"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Librarian",
        ),
        migrations.CreateModel(
            name="Librarian",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ad.myuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
