# Generated by Django 4.2.2 on 2023-08-11 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_loantransaction_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 2, 40, 41, 413370, tzinfo=datetime.timezone.utc)),
        ),
    ]
