# Generated by Django 4.2.2 on 2023-08-07 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_loantransaction_date_expired_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 6, 8, 51, 980485, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
