# Generated by Django 4.2.2 on 2023-07-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0002_alter_profile_date_of_birth_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_time",
            field=models.BooleanField(default=True),
        ),
    ]
