# Generated by Django 4.2.2 on 2023-08-09 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0002_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 16, 13, 56, 16, 604302, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
