# Generated by Django 4.2.2 on 2023-07-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0003_alter_profile_first_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="identity",
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
