# Generated by Django 4.2.2 on 2023-08-12 09:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0003_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrequest",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="readerrequest",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 19, 9, 24, 32, 448045, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
