# Generated by Django 4.2.2 on 2023-08-12 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_loantransaction_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 15, 23, 44, 91007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
