# Generated by Django 4.2.2 on 2023-08-07 01:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0003_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("1", "Active"), ("2", "Inactive")], default="1", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="status",
            field=models.CharField(
                choices=[("1", "Wait"), ("2", "Accept"), ("3", "Decline")],
                default="1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 14, 1, 54, 17, 925749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_loan",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="overdue",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")], default="0", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="returned",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")], default="0", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="readerrequest",
            name="status",
            field=models.CharField(
                choices=[("1", "Wait"), ("2", "Accept"), ("3", "Decline")],
                default="1",
                max_length=2,
            ),
        ),
    ]
