# Generated by Django 4.2.2 on 2023-08-07 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0004_alter_book_status_alter_bookrequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 14, 1, 54, 21, 86865, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
