# Generated by Django 4.2.2 on 2023-07-27 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad", "0004_profile_identity_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="delete_flag",
        ),
        migrations.RemoveField(
            model_name="category",
            name="delete_flag",
        ),
        migrations.RemoveField(
            model_name="language",
            name="delete_flag",
        ),
        migrations.RemoveField(
            model_name="sourcetype",
            name="delete_flag",
        ),
        migrations.CreateModel(
            name="LoanTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_loan", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "date_return",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ad.book"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
