# Generated by Django 4.2.2 on 2023-06-19 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_remove_category_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_created',
        ),
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
