# Generated by Django 4.2.2 on 2023-07-27 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0005_remove_book_delete_flag_remove_category_delete_flag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="status",
        ),
    ]
