# Generated by Django 4.2.2 on 2023-08-13 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0005_alter_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(default="Description cua book ne", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="images/books/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="author",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="image",
            field=models.ImageField(upload_to="images/books/"),
        ),
        migrations.AlterField(
            model_name="bookrequest",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(default="Description cua cate ne", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="images/category/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="language",
            name="fullname",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 20, 17, 26, 38, 643847, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_blog",
            field=models.ImageField(default="aasd", upload_to="images/post/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="main_content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                default="Edit profile for more.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="readerrequest",
            name="email",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="readerrequest",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="readerrequest",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sourcetype",
            name="description",
            field=models.TextField(default="123123", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sourcetype",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
