# Generated by Django 4.2.2 on 2023-08-07 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0005_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 1, 55, 45, 222015, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
