# Generated by Django 4.2.2 on 2023-07-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_sourcetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
