# Generated by Django 4.2.2 on 2023-08-07 23:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0006_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 14, 23, 53, 28, 169504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
