# Generated by Django 4.2.2 on 2023-06-25 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_language_sourcetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('publication_year', models.DateField()),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.language')),
                ('sourcetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.sourcetype')),
            ],
        ),
    ]
