# Generated by Django 4.2.2 on 2023-08-13 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0007_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 20, 17, 28, 16, 984217, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
