# Generated by Django 4.2.2 on 2023-07-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_remove_category_status_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
