# Generated by Django 4.2.2 on 2023-07-27 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0008_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loantransaction",
            name="date_loan",
        ),
        migrations.RemoveField(
            model_name="loantransaction",
            name="date_return",
        ),
    ]
