# Generated by Django 4.2.2 on 2023-08-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0008_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrequest",
            name="image",
            field=models.ImageField(upload_to="images/books_request/"),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 20, 19, 3, 52, 764426, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_content",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="images/avatars/default.jpg", upload_to="images/avatars/"
            ),
        ),
    ]
