# Generated by Django 4.2.2 on 2023-08-16 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0009_alter_bookrequest_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 23, 3, 40, 58, 353263, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
