# Generated by Django 4.2.2 on 2023-07-27 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad", "0009_remove_loantransaction_date_loan_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loantransaction",
            unique_together={("user", "book")},
        ),
    ]
