# Generated by Django 4.2.2 on 2023-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='st_code',
            field=models.CharField(error_messages='Data is already existed', max_length=5, unique=True),
        ),
    ]
