# Generated by Django 4.2.2 on 2023-08-16 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0010_alter_loantransaction_date_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 23, 3, 41, 1, 95591, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
