# Generated by Django 4.2.2 on 2023-07-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad", "0010_alter_loantransaction_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loantransaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ad.book"
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
