# Generated by Django 4.2.2 on 2023-08-07 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_alter_loantransaction_date_expired_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 15, 21, 53, 448749, tzinfo=datetime.timezone.utc)),
        ),
    ]
