# Generated by Django 4.2.2 on 2023-07-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_hotel_alter_sourcetype_st_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('publish_year', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.category')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.language')),
                ('source_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ad.sourcetype')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
