# Generated by Django 4.2.2 on 2023-07-29 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad", "0011_alter_loantransaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loantransaction",
            unique_together={("user", "user")},
        ),
    ]
