# Generated by Django 4.2.2 on 2023-08-07 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_alter_loantransaction_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 15, 48, 37, 885686, tzinfo=datetime.timezone.utc)),
        ),
    ]
