# Generated by Django 4.2.2 on 2023-07-29 02:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ad", "0012_alter_loantransaction_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="loantransaction",
            unique_together={("user", "book")},
        ),
    ]
