# Generated by Django 4.2.2 on 2023-08-09 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_post_image_blog_alter_loantransaction_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_contain',
            field=models.TextField(default='khang'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2023, 8, 16, 6, 23, 14, 872945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
