# Generated by Django 4.2.2 on 2023-07-29 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0013_alter_loantransaction_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantransaction",
            name="date_loan",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
