# Generated by Django 4.2.2 on 2023-08-09 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0014_post_main_contain_alter_loantransaction_date_expired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_contain',
            new_name='main_content',
        ),
        migrations.AlterUniqueTogether(
            name='loantransaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='overdue',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='date_expired',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 7, 21, 22, 692918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='date_loan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='returned',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='loantransaction',
            unique_together={('user', 'book', 'date_loan')},
        ),
    ]
