# Generated by Django 4.2.2 on 2023-07-29 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0014_loantransaction_date_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantransaction",
            name="date_return",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 5, 3, 4, 23, 312991, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
