# Generated by Django 4.2.2 on 2023-08-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_category_image_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Category code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Category image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Category name'),
        ),
    ]
