# Generated by Django 4.2.2 on 2023-07-29 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0015_loantransaction_date_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="loantransaction",
            name="returned",
            field=models.BooleanField(choices=[(0, "No"), (0, "Yes")], default=0),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="date_return",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 5, 3, 6, 34, 420741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
