# Generated by Django 4.2.2 on 2023-07-29 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0017_alter_loantransaction_date_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_return",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 5, 3, 27, 34, 467065, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="returned",
            field=models.CharField(
                choices=[("0", "No"), ("1", "Yes")], default="0", max_length=2
            ),
        ),
    ]
