# Generated by Django 4.2.2 on 2023-07-29 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0018_alter_loantransaction_date_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loantransaction",
            name="date_return",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 5, 3, 28, 28, 819536, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="loantransaction",
            name="returned",
            field=models.BooleanField(choices=[(0, "No"), (1, "Yes")], default=0),
        ),
    ]
