# Generated by Django 4.2.2 on 2023-07-29 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad", "0019_alter_loantransaction_date_return_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loantransaction",
            name="date_return",
        ),
        migrations.AddField(
            model_name="loantransaction",
            name="date_expired",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 5, 4, 3, 59, 718926, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
