# Generated by Django 4.2.2 on 2023-08-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0019_rename_publish_year_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
