# Generated by Django 4.2.2 on 2023-08-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0020_alter_book_image_alter_book_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(null=True, to='ad.category'),
        ),
    ]
