# Generated by Django 4.2.2 on 2023-08-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0021_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='ad.category'),
        ),
    ]
