# Generated by Django 4.2.2 on 2023-08-03 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0023_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
