# Generated by Django 4.2.2 on 2023-08-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0024_alter_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
